//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restoraneo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationClaims
    {
        public int ReservationClaimId { get; set; }
        public string ClientId { get; set; }
        public string ClientUsername { get; set; }
        public int RestaurantId { get; set; }
        public string RestaurantName { get; set; }
        public string NumberOfPersons { get; set; }
        public string DateOfReservation { get; set; }
        public string TimeOfReservation { get; set; }
    }
}
