//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restoraneo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservations
    {
        public int ReservationId { get; set; }
        public int NumberOfPersons { get; set; }
        public int RestaurantId { get; set; }
        public string ApplicationUser_Id { get; set; }
        public int ReservationStatus { get; set; }
        public System.DateTime DateTimeOfReservation { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Restaurants Restaurants { get; set; }
    }
}
