//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restoraneo
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestaurantDishes
    {
        public int RestaurantDishId { get; set; }
        public string Name { get; set; }
        public string Price { get; set; }
        public string Description { get; set; }
        public int RestaurantId { get; set; }
    
        public virtual Restaurants Restaurants { get; set; }
    }
}
